### ISSUE TITLE
how do i use th glitch event (can't find it)

### ISSUE THREAD

**Issue by imdumlol** [miksel1/FNF-ScrewedEngine#12]
### Describe your problem here.

how do i use th glitch event (can't find it)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by MemeHoovy** [comment]
there isn't one

**Comment by imdumlol** [comment]
![ha ha ha](https://user-images.githubusercontent.com/118001986/211139743-3b945ea7-4f5e-45a7-b5c3-8e2b66101328.png)

**Comment by Wither362** [comment]
Use this:
```hx
var glitchShader:WiggleEffect = new WiggleEffect();
glitchShader.effectType = WiggleEffectType.FLAG;
glitchShader.waveAmplitude = 0.1;
glitchShader.waveFrequency = 5;
glitchShader.waveSpeed = 2.25;

"bg".shader = glitchShader.shader;
```

**Comment by imdumlol** [comment]
in lua or haxe?

**Comment by Wither362** [comment]
Haxe

**Comment by imdumlol** [comment]
ok

**Comment by imdumlol** [comment]
where do i put it?

**Comment by Wither362** [comment]
When you create the background or FlxSprite, copy and paste that code, and replace `"bg"` by the FlxSprite's "name"

**Comment by Wither362** [comment]
For example:
```hx
var asa:FlxSprite = new FlxSprite(Paths.image('backgrounds/image'));
// copy and paste code now
```

**Comment by imdumlol** [comment]
is this a stage of event?

**Comment by Wither362** [comment]
Nope

**Comment by imdumlol** [comment]
wdym?

**Comment by Wither362** [comment]
This isn’t a event, I can turn it into a event if you want, but it isn’t an event, in lua isn’t much simpler, but if you want me to turn it into an event, tell me

**Comment by imdumlol** [comment]
i want it to be one

**Comment by Wither362** [comment]
Ok, I’ll add it when I have free time

**Comment by imdumlol** [comment]
thx

**Comment by Wither362** [comment]
Done, go to the chart editor to see how to use it
