### ISSUE TITLE
1: how do i add buttons to the main menu 2: how do i add images in the "main" thing on weeks?

### ISSUE THREAD

**Issue by imdumlol** [miksel1/FNF-ScrewedEngine#13]
### Describe your problem here.

idk how to do it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

nah

**Comment by imdumlol** [comment]
it's for a gapple port

**Comment by Wither362** [comment]
In the `MainMenuState.hx`, there is an array containing all the buttons, add the ones that you want

**Comment by Wither362** [comment]
Main thing? What do you mean?

**Comment by imdumlol** [comment]
like this 
![extra](https://user-images.githubusercontent.com/118001986/211150298-4c169cc7-e4b6-4b7a-b0de-5caffa7aa7bc.png)

**Comment by imdumlol** [comment]
like in freeyplay

**Comment by Wither362** [comment]
Oh, that’s a project I’m working on, the freeplay select state is not ready yet, but you can do it by adding songs with no voices like this: `--Main-–`, when I finish the freeplay select state, I will add them (I don’t think I will… just take that in mind)

**Comment by imdumlol** [comment]
also my dialogue in not working
![Screenshot (166)](https://user-images.githubusercontent.com/118001986/211150559-0c4b187a-feb5-4238-b63a-136d86ae0248.png)

**Comment by imdumlol** [comment]
![3d_dave_wireframe_portrait](https://user-images.githubusercontent.com/118001986/211150636-d098cca5-c4ab-4a55-9fb5-bdee917a6c86.png)

**Comment by imdumlol** [comment]
that is his dialogue

**Comment by Wither362** [comment]
> also my dialogue in not working
> ![Screenshot (166)](https://user-images.githubusercontent.com/118001986/211150559-0c4b187a-feb5-4238-b63a-136d86ae0248.png)

Hm… I didn’t edited dialogue… maybe the json is corrupted or animations are missing

**Comment by Wither362** [comment]
> like this
> ![extra](https://user-images.githubusercontent.com/118001986/211150298-4c169cc7-e4b6-4b7a-b0de-5caffa7aa7bc.png)

Oh! Now I know what you mean! I’ll add them when I get time to do it

**Comment by Wither362** [comment]
> > also my dialogue in not working
> > ![Screenshot (166)](https://user-images.githubusercontent.com/118001986/211150559-0c4b187a-feb5-4238-b63a-136d86ae0248.png)
> 
> Hm… I didn’t edited dialogue… maybe the json is corrupted or animations are missing

Try `Reload Image`, or some of the other buttons

**Comment by imdumlol** [comment]
i will try again

**Comment by imdumlol** [comment]
how do i use the glitch event?

**Comment by imdumlol** [comment]
bro my song does not work cuz it's one second off

**Comment by Wither362** [comment]
> how do i use the glitch event?

Use the `addEventObject(tag:String, object:FlxSprite)` to adding it to the events map, then, use the `Add GlitchEffect` in the events

**Comment by Wither362** [comment]
> bro my song does not work cuz it's one second off

Wdym?

**Comment by imdumlol** [comment]
lik the vocals and inst are a second off

**Comment by Wither362** [comment]
> like the vocals and inst are a second off

Oh freak, that’s bad, really bad

**Comment by imdumlol** [comment]
yeah (thats fl studio for ya)

**Comment by imdumlol** [comment]
but i fixed it

**Comment by imdumlol** [comment]
https://www.youtube.com/watch?v=o5EYG63Vjuk&t=78s

**Comment by Wither362** [comment]
Bro, I haven’t finish it yet! Wait a moment meme!

**Comment by MemeHovy** [comment]
> Bro, I haven’t finish it yet! Wait a moment meme!

sorry 😅

**Comment by MemeHovy** [comment]
this will likely be done as part of #20

**Comment by MemeHovy** [comment]
also @miksel1 I can’t do code rn til next week since I’m at my dads home rn

**Comment by MemeHovy** [comment]
alright, now for the second thing

**Comment by MemeHovy** [comment]
second thing is (untested) but done 👍🏻
