### ISSUE TITLE
BEFORE CREATING ISSUES

### ISSUE THREAD

**Issue by Wither362** [miksel1/FNF-ScrewedEngine#17]
READ THIS FIRST: https://github.com/Theoyeah/PsychEngineDiscussions/discussions?discussions_q=label%3A%22Haxe+Funny+Manual%22

**Comment by seila21-REAL** [comment]
Uh, the page don't exist

**Comment by moxie-coder** [comment]
> Uh, the page don't exist

This engine is literally years old why the fuck are you commenting on like an 4 year old issue
