### ISSUE TITLE
add more shaders

### ISSUE THREAD

**Issue by PHGaming121** [miksel1/FNF-ScrewedEngine#22]
### What feature do you want to get added on the **base** engine?

https://github.com/Clowfoe/IMPOSTOR-UPDATE/blob/main/source/HeatwaveShader.hx
https://github.com/Clowfoe/IMPOSTOR-UPDATE/blob/main/source/BWShader.hx

yes... its the shaders from vs impostor

cool shaders

if u can add them to the engine...

### To test your sight, and reliability, please select the option of what should NOT be requested.

Proper credit that was forgotten

**Comment by MemeHovy** [comment]
they're already in the engine, but can't be used rn

**Comment by PHGaming121** [comment]
ye.... i searched up on the vs impostor github and... i found something

they use some events, look:
![Captura de Tela (145)](https://user-images.githubusercontent.com/76562427/219383850-1186b4cd-522b-4bcf-862a-fc9ec28d7615.png)


if u credit the impostorm team, i think u can use the events and shaders

**Comment by PHGaming121** [comment]
then... u just need to find the correct events

**Comment by MemeHovy** [comment]
yeap

**Comment by MemeHovy** [comment]
pretty sure Wither added most of the shaders, if not all of them

**Comment by Wither362** [comment]
> ye.... i searched up on the vs impostor github and... i found something
> 
> they use some events, look: ![Captura de Tela (145)](https://user-images.githubusercontent.com/76562427/219383850-1186b4cd-522b-4bcf-862a-fc9ec28d7615.png)
> 
> if u credit the impostorm team, i think u can use the events and shaders

Well… I can try…

**Comment by Wither362** [comment]
> pretty sure Wither added most of the shaders, if not all of them

Yep, but _there is always some shader missing._

**Comment by Wither362** [comment]
I’ll add them one of this days:
- Friday (tomorrow)
- Saturday
- Sunday

Because I can’t do it at weekdays

**Comment by Wither362** [comment]
> so uhh... some .frag shaders are not working, try fix this plzzzzzzzzzz

i dont know how to help since i dont know how the shaders work, i might be able to fix it in a couple of days

**Comment by MemeHovy** [comment]
for god sakes, let me help for once

**Comment by Wither362** [comment]
> for god sakes, let me help for once

do it, fix it, please

**Comment by Wither362** [comment]
but fetch origin first, i recommend it

**Comment by MemeHovy** [comment]
alright, I'm just worried about your mental health

**Comment by MemeHovy** [comment]
you've been coding an awful lot

**Comment by Wither362** [comment]
> you've been coding an awful lot

i studied more, so all good!

**Comment by MemeHovy** [comment]
alrght, well I'll atleast try to fix the shaders

**Comment by MemeHovy** [comment]
but I can't promise nothing

**Comment by PHGaming121** [comment]
so uhhh..... how is the shader fix work???

**Comment by MemeHovy** [comment]
> so uhhh..... how is the shader fix work???

just removes the need for glsl version (so that maybe it auto detects?) and such

**Comment by PHGaming121** [comment]
i just removed the add chromatic aberration, because i found another one(its a "cooler CA shader")

**Comment by PHGaming121** [comment]
also, its already added on lua
i think thats the code we need for FunkinLua

		Lua_helper.add_callback(lua, "addChromaticAbberationEffect", function(camera:String,chromeOffset:Float = 0.005) {
			
			PlayState.instance.addShaderToCamera(camera, new ChromaticAberrationEffect(chromeOffset));
			
		});

**Comment by MemeHovy** [comment]
it's literally the same thing -____-

**Comment by PHGaming121** [comment]
Then WHY THIS IS NOT IMPLEMENTED ON THE ENGINE?????

**Comment by PHGaming121** [comment]
sorry for caps

**Comment by MemeHovy** [comment]
> Then WHY THIS IS NOT IMPLEMENTED ON THE ENGINE?????

cuz we already have a chromatic shader in the engine

**Comment by PHGaming121** [comment]
Ye i know but... i want to add that in my songs?

I mean, how to do that?

**Comment by MemeHovy** [comment]
> Ye i know but... i want to add that in my songs?
> 
> I mean, how to do that?

use `globalChromaticAberration.amount`

**Comment by MemeHovy** [comment]
but also make sure to remove this block first
![image](https://github.com/miksel1/FNF-ScrewedEngine/assets/124418090/2fd9625e-b5ce-4d7f-a9b4-9de1a2ee692e)

**Comment by PHGaming121** [comment]
I mean use in lua, like glitch effect

**Comment by MemeHovy** [comment]
oh, `setProperty('globalChromaticAberration.amount', amount)`

**Comment by PHGaming121** [comment]
now one more thing....

HOW CAN I FIX THE FRAG SHADERS???????

ALMOST EVERY SHADER I HAVE works on default psych, but idk why it doesnt work on screwed engine

**Comment by PHGaming121** [comment]
> setProperty('globalChromaticAberration.amount', amount)

and to set the shader in a camera or object, like camGame, what code should i use?

**Comment by MemeHovy** [comment]
> > setProperty('globalChromaticAberration.amount', amount)
> 
> and to set the shader in a camera or object, like camGame, what code should i use?

it’s set to camGame by default if iirc, but I will add code for lua shaders soon

**Comment by MemeHovy** [comment]
gonna close this due to being long outdated, and also I’ll soon optimize the shader system I implemented
