### ISSUE TITLE
Ayo, you guys have forgotten to credit me for the GameJolt thingie

### ISSUE THREAD

**Issue by GamerPablito** [miksel1/FNF-ScrewedEngine#35]
### What needs to be documented?

Please guys, it's one of the requirements of use according to the license I assigned to my project :)

**Comment by GamerPablito** [comment]
Nvm, just kidding lol

**Comment by MemeHovy** [comment]
lol

**Comment by GamerPablito** [comment]
Closed because I just noticed lmao @MemeHovy

**Comment by MemeHovy** [comment]
it's okay lol
