### ISSUE TITLE
Native Notetypes fix

### ISSUE THREAD

**Issue by PHGaming121** [miksel1/FNF-ScrewedEngine#37]
### Describe your bug here.

I tried to add a song from strident crisis(the song called "Incinerate"), but it give me an error saying something like Note.setNotetype,etc

Then, it give this:
Uncaught error: Null Object Reference

Then, i opened the incinerate.json file and found 2 notetypes(No Animation and Alt Animation)

Why do i think the native notetypes are glitched!??!!?!?

### Command Prompt/Terminal logs (if existing)

```bash
Note.hx (line 201, Method(Note, set_noteType))
PlayState.hx (line 2685, Method(PlayState, generateSong))
PlayState.hx (line 1162, Method(PlayState, create))
flixel/FlxGame.hx (line 642, Method(flixel.FlxGame, switchState))
flixel/FlxGame.hx (line 729, Method(flixel.FlxGame, update))
flixel/FlxGame.hx (line 682, Method(flixel.FlxGame, step))
flixel/FlxGame.hx (line 550, Method(flixel.FlxGame, onEnterFrame))
openfl/events/EventDispatcher.hx (line 402, Method(openfl.events.EventDispatcher, __dispatchEvent))
openfl/display/DisplayObject.hx (line 1399, Method(openfl.display.DisplayObject, __dispatch))

Uncaught Error: Null Object Reference
Please report this error to Wither362 (Discord: Wither#9781, GitHub: Wither362),
or MemeHoovy (Discord: MemeHoovy#0001, GitHub: https://github.com/MemeHovy)
or by the GitHub page: "https://github.com/miksel1/FNF-ScrewedEngine"

> Crash Handler written by: sqirra-rng

```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, i edited nothing

**Comment by MemeHovy** [comment]
hmm, I'll look into this when I have the time to

**Comment by PHGaming121** [comment]
i edited the issue so now u can see the error

**Comment by MemeHovy** [comment]
cool
