### ISSUE TITLE
Just try to fix this

### ISSUE THREAD

**Issue by PHGaming121** [miksel1/FNF-ScrewedEngine#41]
### Describe your bug here.

![230111402-c1c43ebc-8a7d-4c51-8396-f656456622ef](https://github.com/miksel1/FNF-ScrewedEngine/assets/76562427/d0fa7b96-cde5-499f-8bdc-9dc05a3c04d4)

TO FIX:
That thing
FIX THE SHADERS IDK HOW AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHH

to add
Lua code for shaders
**OPTIONAL** custom menu editor

### Command Prompt/Terminal logs (if existing)

```bash
PlayState.hx (line 3729, Method(PlayState, update))
flixel/group/FlxGroup.hx (line 764, Method(flixel.group.FlxTypedGroup, forEachAlive))
PlayState.hx (line 3723, Method(PlayState, update))
flixel/FlxState.hx (line 220, Method(flixel.FlxState, tryUpdate))
flixel/FlxGame.hx (line 752, Method(flixel.FlxGame, update))
flixel/FlxGame.hx (line 682, Method(flixel.FlxGame, step))
flixel/FlxGame.hx (line 550, Method(flixel.FlxGame, onEnterFrame))
openfl/events/EventDispatcher.hx (line 402, Method(openfl.events.EventDispatcher, __dispatchEvent))
openfl/display/DisplayObject.hx (line 1399, Method(openfl.display.DisplayObject, __dispatch))

Uncaught Error: Null Object Reference
Please report this error to Wither362 (Discord: Wither#9781, GitHub: Wither362),
or MemeHoovy (Discord: MemeHoovy#0001, GitHub: https://github.com/MemeHovy)
or by the GitHub page: "https://github.com/miksel1/FNF-ScrewedEngine"

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no edits on code

**Comment by PHGaming121** [comment]
re-opened this because THAT AAAAAAAAAAAAAAAHHHHHIOUFHSDOFHSDFSFUSFSIFS ISNT FIXED

**Comment by Wither362** [comment]
Line 3590 (the picture one) doesn’t match with the line 3729 (the one in the “terminal prompts”

**Comment by PHGaming121** [comment]
WHERE DID THE NOTES GO???!!!

**Comment by Wither362** [comment]
Try fixing the XML from the notes. ALL. STRUMNOTES AND 3D NOTES.

**Comment by MemeHovy** [comment]
> Try fixing the XML from the notes. ALL. STRUMNOTES AND 3D NOTES.

I added an insurance thing to make sure it won't crash if it doesn't have the animation

**Comment by MemeHovy** [comment]
@PHGaming121 does it crash still or nah?

**Comment by PHGaming121** [comment]
> @PHGaming121 does it crash still or nah?

THAT HELPS?
![Captura de Tela (328)](https://github.com/miksel1/FNF-ScrewedEngine/assets/76562427/2d44f47d-c5e6-427d-b54d-67c80365dc6f)

**Comment by MemeHovy** [comment]
okay, well, if we can reproduce the issue that would be great

**Comment by MemeHovy** [comment]
can you send us the mod?

**Comment by MemeHovy** [comment]
why?

**Comment by Wither362** [comment]
> why?

Bro, it’s a mod in development, they won’t let us see it until it gets finished and published

**Comment by MemeHovy** [comment]
> > why?
> 
> Bro, it’s a mod in development, they won’t let us see it until it gets finished and published

well, if we can't reproduce the issue, it's only gonna make it harder to fix it

**Comment by PHGaming121** [comment]
I can send a video showing what and when exactly the error appears(OBS: THIS IS FROM A OLD BUILD, BUT THE THING HAPPENS AT THE SAME TIME, SAME WAY)

**Comment by PHGaming121** [comment]
Well here it is:

**Comment by PHGaming121** [comment]
Have to send the link from discord because cant attach video here

**Comment by MemeHovy** [comment]
> https://discord.com/channels/1038508090259157043/1038508091848806461/1100472103288983603

we can't access that

**Comment by MemeHovy** [comment]
you have to send the video, not the channel link from discord

**Comment by PHGaming121** [comment]
https://github.com/miksel1/FNF-ScrewedEngine/assets/76562427/9f927aa8-da80-4dd8-b6d5-dd59f000cd9b
i reduced the quality of the vid so it wont pass 10MB

also the video is shorter, but we can see where the error appears

**Comment by PHGaming121** [comment]
WHY IT IS A LINK???!!!???!?!?!?!?!?

**Comment by PHGaming121** [comment]
didnt worked
using the latest commit

**Comment by MemeHovy** [comment]
@PHGaming121 good news for you, I finally fixed it!
