### ISSUE TITLE
Download Link Is Broken

### ISSUE THREAD

**Issue by BambiGaming2022** [miksel1/FNF-ScrewedEngine#43]
### What is your question?

outdated windows build link moment

**Comment by MemeHovy** [comment]
look at actions builds then

**Comment by BambiGaming2022** [comment]
ok then

**Comment by BambiGaming2022** [comment]
actions builds keep failing in other times

**Comment by MemeHovy** [comment]
I'll fix it later

**Comment by BambiGaming2022** [comment]
ok

**Comment by BambiGaming2022** [comment]
Windows Build is works now

Only Windows Build is working

**Comment by BambiGaming2022** [comment]
Lol

**Comment by MemeHovy** [comment]
> Thanks for build download

np lol
