### ISSUE TITLE
Nice Timing

### ISSUE THREAD

**Issue by BambiGaming2022** [miksel1/FNF-ScrewedEngine#44]
### Describe your bug here.

I got this error and its pops out in nice timing
![image](https://github.com/miksel1/FNF-ScrewedEngine/assets/116512242/93b9b1a6-6a33-4e99-8c23-9c0456cb16f7)

### Command Prompt/Terminal logs (if existing)

```bash
No
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by BambiGaming2022** [comment]
i am not modding

**Comment by MemeHovy** [comment]
seems like something in the shader is trying to pass a var from vec4 to something that takes a vec2

**Comment by BambiGaming2022** [comment]
yea, now i am stuck in this endless loop

**Comment by MemeHovy** [comment]
I've also been unable to reproduce this issue (I've literally been to this title screen a million times now), so what we can do is either send over a project that'll produce some GLSL info that I need you to send back over, or you can compile the engine in debug mode so I can see some GLSL info

**Comment by BambiGaming2022** [comment]
![image](https://github.com/miksel1/FNF-ScrewedEngine/assets/116512242/e5d41f91-7bff-4f2e-b9cf-ba6df59df556)
did i fucked up something

**Comment by MemeHovy** [comment]
one sec

**Comment by MemeHovy** [comment]
I think I fixed it in 9d3f08a09fc155924ead88fbb3e6e477a5566248

**Comment by MemeHovy** [comment]
try compiling now

**Comment by BambiGaming2022** [comment]
![image](https://github.com/miksel1/FNF-ScrewedEngine/assets/116512242/3f11f2d8-d667-4600-b84a-f7cde36f6dae)
cant even remove this folder

**Comment by BambiGaming2022** [comment]
i think this is fucked up

**Comment by BambiGaming2022** [comment]
let me restart the PC

**Comment by BambiGaming2022** [comment]
restarted and removed assets and recloned folder

**Comment by Wither362** [comment]
> ![image](https://user-images.githubusercontent.com/116512242/241213600-e5d41f91-7bff-4f2e-b9cf-ba6df59df556.png)
> did i fucked up something

That happened to me too. I had to download everything and manually restore it myself.

**Comment by BambiGaming2022** [comment]
I think you need just to fix it not checking

**Comment by BambiGaming2022** [comment]
shader is just breaks your game

**Comment by Wither362** [comment]
It’s not shaders. It’s flixel.

**Comment by BambiGaming2022** [comment]
I mean in this engine not flixel
