### ISSUE TITLE
search bar crash

### ISSUE THREAD

**Issue by Joalor64GH** [miksel1/FNF-ScrewedEngine#49]
### Describe your bug here.

i tried to use the search bar and this happened:
![vs  DAB_ Screwed Engine 7_22_2023 3_22_54 PM](https://github.com/miksel1/FNF-ScrewedEngine/assets/99079926/6d44c62b-9445-415a-a46f-b46551a0504f)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No.

**Comment by MemeHovy** [comment]
hmmm, I'll look into this

**Comment by Wither362** [comment]
Ok, thanks for reporting

**Comment by Wither362** [comment]
Btw, which “version” of the engine are you using?

**Comment by Joalor64GH** [comment]
0.1.0

**Comment by Wither362** [comment]
Ok, that’s already fixed in the new update

**Comment by Wither362** [comment]
> Ok, that’s already fixed in the new update

I think

**Comment by MemeHovy** [comment]
> Ok, that’s already fixed in the new update

👍
