### ISSUE TITLE
no source code needed for engine download

### ISSUE THREAD

**Issue by randomslovakguy** [miksel1/FNF-ScrewedEngine#52]
### What is your question?

could you make a download thing (like almost every engine has) that you dont need source code to download it?

**Comment by moxie-coder** [comment]
did you seriously not bother to look at [this](https://github.com/miksel1/FNF-ScrewedEngine/releases)?

**Comment by randomslovakguy** [comment]
well at what?

**Comment by randomslovakguy** [comment]
and what in there? theres just source code files for download

**Comment by moxie-coder** [comment]
there's artifacts in https://github.com/miksel1/FNF-ScrewedEngine/actions I'm currently running a build, you can get one when it finishes, I have to rerun it since they all expired

**Comment by moxie-coder** [comment]
here, https://github.com/miksel1/FNF-ScrewedEngine/actions/runs/7865438539/artifacts/1237017545

**Comment by randomslovakguy** [comment]
thanks :)

**Comment by moxie-coder** [comment]
np
