### ISSUE TITLE
About my bambi engine

### ISSUE THREAD

**Issue by BambiGaming2022** [miksel1/FNF-ScrewedEngine#6]
### What is your question?

Can be ported my menu to this engine

**Comment by Wither362** [comment]
I don’t understand it, what menu?

**Comment by BambiGaming2022** [comment]
[MainMenuState.zip](https://github.com/miksel1/FNF-ScrewedEngine/files/10091598/MainMenuState.zip)

**Comment by BambiGaming2022** [comment]
oh sorry, your already passed the file
