### ISSUE TITLE
hhhhhhhhmmmmmmmmmmmmmmmppppp

### ISSUE THREAD

**Issue by imdumlol** [miksel1/FNF-ScrewedEngine#7]
### Describe your problem here.

source/PlayState.hx:3530: characters 6-34 : Cannot access field or identifier frames for writing

can't compile it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x86/x32

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by imdumlol** [comment]
hello??

**Comment by imdumlol** [comment]
ok

**Comment by miksel1** [comment]
try now ig

**Comment by Wither362** [comment]
Can you pass the file **by discord**?
